version: '3'
networks:
  monitoring:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheusdata:/prometheus
      - prometheus:/etc/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
      - grafana:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - monitoring
  node-application-monitoring-app:
    build:
      context: node-js-app
    image: vaued.azurecr.io/node-js-app
    container_name: node-js-app
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
volumes:
  prometheusdata:
    driver: azure_file
    driver_opts:
      share_name: prometheusdata
      storage_account_name: vauedstorage
  grafanadata:
    driver: azure_file
    driver_opts:
      share_name: grafanadata
      storage_account_name: vauedstorage
  promethus:
    driver: azure_file
    driver_opts:
      share_name: promethus
      storage_account_name: vauedstorage
  grafana:
    driver: azure_file
    driver_opts:
      share_name: grafana
      storage_account_name: vauedstorage