{
 "title": "Request Flow Dashboard",
 "tags": [ "nodejs" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (route, method, code) / sum(rate(http_request_duration_seconds_count[5m])) by (route, method, code)",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (route, method, code)  * 60",
     "legendFormat": "{{service}} - {{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (increase(http_request_duration_seconds_bucket{le=\"0.3\"}[1d])) / sum by (app) (increase(http_request_duration_seconds_count[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Average Throughput",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (route, method, code)  * 60",
     "legendFormat": "{{service}} - {{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "NUmber of Failed Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])* 60)  by (route, method, code)"
    }
   ]
  },
  {
   "title": "Node Reqeust Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(sum by (le) (increase(http_request_duration_seconds_bucket[1d])), \"le\", \"Inf\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (route, method, code) / sum(rate(http_request_duration_seconds_count[5m])) by (route, method, code)",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"^5..$\"}[1m]))/sum(increase(http_request_duration_seconds_count[1m]))"
    }
   ]
  }
 ]
}